### ISSUE TITLE
Pretreatment method

### ISSUE THREAD

**Issue by LXP-Never** [isamilefchik/super-resolution-audio-stretch#1]
Can you tell me how to get the low frequency data of fugue_1_plucks_slow.wav

**Comment by isamilefchik** [comment]
I rendered a MIDI file of a Bach fugue (the MIDI files I used were sourced from [here](http://www.bachcentral.com/midiindexcomplete.html)) both at the true BPM and 0.5x the true BPM. I used a realistic plucked-string synthesizer as well as the application Reaper to do this. The 0.5x BPM version is fugue_1_plucks_slow.wav. I would like to be clear though that I have not been able to get this project working. It is still in progress, even though it has been dormant for some time. The code on Git right now is not able to produce good results.
